### ISSUE TITLE
Reducing binary size even more

### ISSUE THREAD

**Issue by dcodeIO** [krisselden/xoroshiro128starstar#1]
* Inlining `nextUint64` (using `@inline`) reduces binary size to 356 bytes
* Removing the export of and inlining `nextUint53` as well gets us to 319 bytes
* Compiling with `--noDebug`, thus excluding the names section, brings it down to 262 bytes

Keep it up! :)

**Comment by krisselden** [comment]
Thanks for the feedback.

So VS Code reports errors "decorators are not valid here" for decorators on functions, which is a little distracting, have you thought about using jsdoc tags?  `/** @inline */` or just a special comment `// @inline`?

**Comment by krisselden** [comment]
Added a benchmark, not that Math.random is slow, but I was curious.

I also wanted to compare it to the seedrandom npm package.

The whole point is I believe that there are useful things that webassembly can do, and most usages seem to port whole apps, or a library that brings a large standard library with it.
